import type { Metadata } from "next";
// import { Geist, Geist_Mono, DM_Serif_Display } from "next/font/google";
// import { DM_Serif_Display, Roboto_Flex, Roboto_Serif } from "next/font/google";

import { Inria_Serif } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const inriaSerif = Inria_Serif({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  style: ["normal", "italic"],
  variable: "--font-inria-serif",
});


// const dmSerifDisplay = DM_Serif_Display({
//   subsets: ["latin"],
//   weight: "400", // Only 400 is available for DM Serif Display
//   style: ["normal", "italic"],
// });

// const robotoFlex = Roboto_Flex({
//   subsets: ["latin"],
//   weight: ["400", "700"], // Adjust as needed
// });

// const robotoSerif = Roboto_Serif({
//   subsets: ["latin"],
//   weight: ["400", "700"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inriaSerif.variable} font-serif antialiased`}>
        {children}
      </body>
    </html>
  );
}
